### ISSUE TITLE
Elliptic Curve Params

### ISSUE THREAD

**Issue by kevaundray** [mndrix/btcutil#1]
I believe that the underlying GoLang elliptic curve library takes a=-3 as a constant param, whereas bitcoin uses a=0?

**Comment by mndrix** [comment]
Can you write a failing test case showing where the  package and Bitcoin produce different results? If so, we can investigate a solution.

I haven't used this library in years, so I may not be the best one to implement changes, but I'd be glad to review a pull request.

**Comment by kevaundray** [comment]
That's the strange thing. For Bitcoin it produces correct results. It says in the GoLang crypto library that a=-3, I was hoping that you may have known why it worked, it does not work if the curve is changed to secp256r1 and we test against a crypto that uses it.
